# Generated by Django 2.0.1 on 2018-03-10 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KbArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('Kb_text', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Linker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('urly', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ModelNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('note_text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapps.Company')),
                (
                'department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapps.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(blank=True, max_length=4, null=True)),
                ('address_line1',
                 models.CharField(blank=True, max_length=200, null=True, verbose_name='Address Line 1')),
                ('address_line2',
                 models.CharField(blank=True, max_length=200, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_num', models.CharField(max_length=200)),
                ('group',
                 models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coreapps.Group')),
                ('person',
                 models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coreapps.Person')),
                ('place',
                 models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coreapps.Place')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapps.Place'),
        ),
        migrations.AddField(
            model_name='modelnumber',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapps.Place'),
        ),
        migrations.AddField(
            model_name='department',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapps.Place'),
        ),
    ]
