# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='desc',
            new_name='description',
        ),
    ]
