# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapps', '0003_auto_20171212_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='places',
            name='address_line1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='places',
            name='address_line2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address Line 2'),
        ),
    ]
