# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapps', '0004_auto_20171216_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companies',
            new_name='Company',
        ),
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='KbArticles',
            new_name='KbArticle',
        ),
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
        migrations.RenameModel(
            old_name='ModelNumbers',
            new_name='ModelNumber',
        ),
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
        migrations.RenameModel(
            old_name='People',
            new_name='Person',
        ),
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
        migrations.RenameModel(
            old_name='Things',
            new_name='Thing',
        ),
    ]
