# Generated by Django 2.0.1 on 2018-01-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('coreapps', '0005_auto_20171216_1633'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='Linker',
        ),
        migrations.AlterField(
            model_name='place',
            name='number',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
